# Based on KubeFlex PR #384 - Correct format for multiple PostCreateHooks

{{- range .Values.WDSes }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: {{ .name }}
spec:
  backend: shared
  type: {{ .type | default "k8s" }}
  postCreateHooks:
    - hookName: transport-controller
      vars:
        ControlPlaneName: {{ .name }}
        ITSName: {{ .ITSName | default "" }}
        APIGroups: {{ .APIGroups | default "" }}
    - hookName: kubestellar-controller  
      vars:
        ControlPlaneName: {{ .name }}
        ITSName: {{ .ITSName | default "" }}
        APIGroups: {{ .APIGroups | default "" }}
{{- end }}