{{- range .Values.WDSes }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: {{ .name }}
spec:
  backend: shared
  type: {{ .type | default "k8s" }}
  postCreateHooks:
    - hookName: transport-controller
    - hookName: kubestellar-controller
      vars:
        APIGroups: {{ .APIGroups | default "" }}
  globalVars:
    ControlPlaneName: {{ .name }}
    ITSName: {{ .ITSName | default "" }}
{{- end }}