{{- range .Values.WDSes }}
---
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  name: {{ .name }}
spec:
  backend: shared
  type: {{ .type | default "k8s" }}
  postCreateHooks:
    - transport-controller
    - kubestellar-controller
  postCreateHookVars:
    ITSName: {{ .ITSName | default "" }}
    APIGroups: {{ .APIGroups | default "" }}
{{- end }}
