name: Static Analysis

on:
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yaml"
  push:
    branches: [main, master]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.59.1
          args: --timeout=10m --issues-exit-code=0 --config=.golangci.yaml
          only-new-issues: true

      - name: Add Lint Summary
        if: always()
        run: |
          echo "### Static Analysis" >> $GITHUB_STEP_SUMMARY
          echo "A non-blocking static analysis check ran for OpenSSF badge visibility." >> $GITHUB_STEP_SUMMARY
          echo "Config used: .golangci.yaml" >> $GITHUB_STEP_SUMMARY
